# 配置 Mysql 需要修改的常量
MYSQL_HOST: 139.155.90.176:3306
MYSQL_USERNAME: fund
MYSQL_PASSWORD: fund

server:
  port: 8089
  servlet:
    context-path: /Crawler
  #设置头的大小
  max-http-header-size: 102400
# 指定目录
uploadFilePath: /usr/app

# 默认的查询接口配置
default:
  # 展示今天的股票信息
  show_day_url: https://hq.sinajs.cn/list={0}
  # 展示所有的股票信息
  all_stock_url: >
    https://20.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=10000000&np=1&fid=f3&fields={0}&fs=m:0+t:6,m:0+t:13,m:0+t:80,m:1+t:2,m:1+t:23,b:MK0021,b:MK0022,b:MK0023,b:MK0024
  # 查询这个股票的历史信息
  stock_history_url: >
    http://push2his.eastmoney.com/api/qt/stock/kline/get?
    fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61
    &klt=101&fqt=1&secid={}&beg={}&end={}
  stock_history_download_url: >
    http://quotes.money.163.com/service/chddata.html?code={0}&start={1}&end={2}&fields=TCLOSE;HIGH;LOW;TOPEN;LCLOSE;CHG;PCHG;TURNOVER;VOTURNOVER;VATURNOVER;TCAP;MCAP
  #k线图
  min_url: http://image.sinajs.cn/newchart/min/n/{0}.gif
  daily_url: http://image.sinajs.cn/newchart/daily/n/{0}.gif
  weekly_url: http://image.sinajs.cn/newchart/weekly/n/{0}.gif
  monthly_url: http://image.sinajs.cn/newchart/monthly/n/{0}.gif
# 引入 数据库的相关配置
spring:
  main:
    allow-bean-definition-overriding: true
  # 配置 json
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/stock?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 100
    maxActive: 100
    minIdle: 100
  #配置上传的文件信息
  servlet:
    multipart:
      max-file-size: 100MB   # 服务器端文件大小限制
      max-request-size: 100MB  # 客户端请求文件大小限制
#整合mybatis时使用的。   去掉整合 MyBatis的配置信息
mybatis-plus:
  # 配置 mapper文件的位置
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  # 配置日志
  configuration:
    map-underscore-to-camel-case: true #  配置数据库表的列别名设置
    # 关闭mybatis一级缓存，防止事务和缓存同时打开引起的查询异常
    local-cache-scope: STATEMENT
    #查看mybatis的SQL, 线上服务器关闭
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag   # 逻辑删除的字段
      logic-not-delete-value: 1  # 正常状态下，该字段的值
      logic-delete-value: 0      # 删除后，该字段的值
      table-underline: true # 驼峰方式转换
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
